// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/api/file/index.ts";
import * as $1 from "./routes/api/upload.ts";
import * as $2 from "./routes/file/[id].tsx";
import * as $3 from "./routes/folder/[id].tsx";
import * as $4 from "./routes/index.tsx";
import * as $$0 from "./islands/CreateButton.tsx";
import * as $$1 from "./islands/CreateModal.tsx";
import * as $$2 from "./islands/DeleteButton.tsx";
import * as $$3 from "./islands/FileUpload.tsx";

const manifest = {
  routes: {
    "./routes/api/file/index.ts": $0,
    "./routes/api/upload.ts": $1,
    "./routes/file/[id].tsx": $2,
    "./routes/folder/[id].tsx": $3,
    "./routes/index.tsx": $4,
  },
  islands: {
    "./islands/CreateButton.tsx": $$0,
    "./islands/CreateModal.tsx": $$1,
    "./islands/DeleteButton.tsx": $$2,
    "./islands/FileUpload.tsx": $$3,
  },
  baseUrl: import.meta.url,
};

export default manifest;
